/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Dark mode (default)
        'inverse-primary': '#005ac2',
        'on-secondary': '#490080',
        'surface-container': 'var(--surface-container)',
        'on-surface': 'var(--on-surface)',
        'primary-fixed-dim': '#adc6ff',
        'tertiary-container': '#00a572',
        'primary': 'var(--primary)',
        'secondary-container': '#7c03d3',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed-variant': '#6800b4',
        'outline-variant': 'var(--outline-variant)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#001a42',
        'on-tertiary-container': '#00311f',
        'surface-bright': '#39393b',
        'tertiary-fixed-dim': '#4edea3',
        'primary-fixed': '#d8e2ff',
        'surface': 'var(--surface)',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-highest': 'var(--surface-container-highest)',
        'inverse-surface': '#e4e2e4',
        'on-secondary-fixed': '#2c0051',
        'secondary': 'var(--secondary)',
        'primary-container': 'var(--primary-container)',
        'error-container': '#93000a',
        'on-primary': 'var(--on-primary)',
        'surface-dim': '#131315',
        'on-tertiary-fixed': '#002113',
        'on-background': 'var(--on-surface)',
        'surface-container-low': 'var(--surface-container-low)',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'on-tertiary': '#003824',
        'secondary-fixed': '#f0dbff',
        'inverse-on-surface': '#303032',
        'on-primary-container': 'var(--on-primary-container)',
        'secondary-fixed-dim': '#ddb8ff',
        'surface-tint': '#adc6ff',
        'surface-variant': '#353437',
        'outline': 'var(--outline)',
        'background': 'var(--surface)',
        'on-secondary-container': '#dfbcff',
        'tertiary': 'var(--tertiary)',
        'surface-container-high': 'var(--surface-container-high)',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
